FROM postgres:9.6

# Create a user to avoid running containers as root in production
RUN addgroup --system yllorca \
    && adduser --system --ingroup yllorca yllorca
    
# Copy entrypoint script which waits for the db to be ready
COPY --chown=yllorca:yllorca create-multiple-postgres-databases.sh /docker-entrypoint-initdb.d/create-multiple-postgres-databases.sh
RUN chmod +x /docker-entrypoint-initdb.d/create-multiple-postgres-databases.sh

# The production server starts by default when the container starts
CMD ["create-multiple-postgres-databases.sh"]